/* eslint-disable @typescript-eslint/no-require-imports */
const {test,afterEach,after}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const ts=require('typescript');const {JSDOM}=require('jsdom');
const dom=new JSDOM('<html><body></body></html>',{url:'http://localhost'});global.window=dom.window;global.document=dom.window.document;global.HTMLElement=dom.window.HTMLElement;
global.IntersectionObserver=class{constructor(callback){this.callback=callback;}observe(){this.callback([{isIntersecting:true}]);}disconnect(){}};
const React=require('react');const {render,screen,waitFor,cleanup}=require('@testing-library/react');const originalFetch=global.fetch;afterEach(()=>{cleanup();global.fetch=originalFetch;});after(()=>dom.window.close());
function load(file,deps={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{esModuleInterop:true,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText)(name=>deps[name]??require(name),m,m.exports);return m.exports;}
const helpers=load('lib/images/artist.ts');
const {ArtistPortrait}=load('components/ArtistPortrait.tsx',{'@/lib/images/artist':helpers,'next/image':({src,alt,onError})=>{if(!helpers.artistImageUrl(src))throw Error('Unsupported image URL');return React.createElement('img',{src,alt,onError});}});
test('Wikimedia thumbnail domains are supported; unknown portrait sources are rejected',()=>{assert.equal(helpers.artistImageUrl('https://thumb.wikimedia.org/wikipedia/commons/future.jpg'),'https://thumb.wikimedia.org/wikipedia/commons/future.jpg');assert.equal(helpers.artistImageUrl('https://other.example/future.jpg'),null);assert.equal(helpers.artistImageUrl({url:'invalid'}),null);assert.equal(helpers.artistImageUrl('javascript:alert(1)'),null);assert.match(fs.readFileSync('next.config.ts','utf8'),/hostname: "thumb\.wikimedia\.org"/);});
test('Future refers to the musician instead of the article about time',async()=>{const calls=[];global.fetch=async(url)=>{calls.push(url);if(url.includes('/summary/Future%20(rapper)'))return Response.json({description:'American rapper',thumbnail:{source:'https://thumb.wikimedia.org/wikipedia/commons/future.jpg'}});if(url.includes('/w/api.php'))return Response.json({query:{search:[{title:'Future (rapper)'}]}});return Response.json({description:'Time that is to come',thumbnail:{source:'https://thumb.wikimedia.org/wikipedia/commons/time.jpg'}});};const {GET}=load('app/api/artist-image/route.ts',{'@/lib/images/artist':helpers});const response=await GET(new Request('http://localhost/api/artist-image?name=Future'));assert.deepEqual(await response.json(),{url:'https://thumb.wikimedia.org/wikipedia/commons/future.jpg'});assert.equal(calls.length,3);});
test('an invalid portrait response cannot crash artist results',async()=>{let fetched=false;global.fetch=async()=>{fetched=true;return Response.json({url:'https://unconfigured.example/future.jpg'});};render(React.createElement(ArtistPortrait,{name:'Future'}));await waitFor(()=>assert.equal(fetched,true));assert.equal(screen.queryByRole('img'),null);assert.ok(screen.getByText('♪'));});
test('a valid Wikimedia thumbnail renders Future successfully',async()=>{global.fetch=async()=>Response.json({url:'https://thumb.wikimedia.org/wikipedia/commons/future.jpg'});render(React.createElement(ArtistPortrait,{name:'Future'}));assert.equal((await screen.findByRole('img',{name:'Future'})).getAttribute('src'),'https://thumb.wikimedia.org/wikipedia/commons/future.jpg');});
